apiVersion: v1
kind: Service
metadata:
  name: theposterdb
  namespace: media
  labels:
    app.kubernetes.io/name: theposterdb
    app.kubernetes.io/part-of: media-stack
spec:
  selector:
    app: theposterdb
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
