apiVersion: v1
kind: Service
metadata:
  name: janitorr
  namespace: media
  labels:
    app.kubernetes.io/name: janitorr
    app.kubernetes.io/part-of: media-stack
spec:
  selector:
    app: janitorr
  type: ClusterIP
  ports:
  - name: http
    port: 8978
    targetPort: 8978
